#!/bin/bash

# Supabase Type Generation Script
# This script generates TypeScript types from your Supabase database schema

set -e

# Load environment variables from .env file if it exists
if [ -f .env ]; then
    export $(cat .env | grep -v '^#' | xargs)
fi

# Load environment variables from .env.local file if it exists
if [ -f .env.local ]; then
    export $(cat .env.local | grep -v '^#' | xargs)
fi

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}🔧 Generating Supabase types...${NC}"

# Check if required environment variables are set
if [ -z "$NEXT_PUBLIC_SUPABASE_PROJECT_ID" ]; then
    echo -e "${RED}❌ Error: NEXT_PUBLIC_SUPABASE_PROJECT_ID environment variable is not set${NC}"
    echo -e "${YELLOW}💡 Please set it in your .env.local file${NC}"
    exit 1
fi

if [ -z "$SUPABASE_ACCESS_TOKEN" ]; then
    echo -e "${YELLOW}⚠️  Warning: SUPABASE_ACCESS_TOKEN not set. You may need to run 'supabase login' first${NC}"
fi

# Create types directory if it doesn't exist
TYPES_DIR="src/types"
if [ ! -d "$TYPES_DIR" ]; then
    echo -e "${BLUE}📁 Creating types directory...${NC}"
    mkdir -p "$TYPES_DIR"
fi

# Generate types
echo -e "${BLUE}📝 Running Supabase CLI to generate types...${NC}"

# Check if we're using local development or remote
if [ "$1" = "--local" ]; then
    echo -e "${YELLOW}🔧 Using local Supabase instance...${NC}"
    npx supabase gen types typescript --local > "$TYPES_DIR/supabase.ts"
else
    echo -e "${YELLOW}🌐 Using remote Supabase instance...${NC}"
    npx supabase gen types typescript \
        --project-id "$NEXT_PUBLIC_SUPABASE_PROJECT_ID" \
        --schema public > "$TYPES_DIR/supabase.ts"
fi

# Add header comment to the generated file
TYPES_FILE="$TYPES_DIR/supabase.ts"
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Create header content
HEADER="// Auto-generated by Supabase CLI
// Run 'npm run generate-types' to regenerate
// Last generated: $TIMESTAMP
// 
// To use these types in your components:
// import type { Database } from '@/types/supabase'
//
"

# Prepend header to the file
echo -e "$HEADER$(cat $TYPES_FILE)" > "$TYPES_FILE"

echo -e "${GREEN}✅ Types generated successfully!${NC}"
echo -e "${BLUE}📄 Types saved to: $TYPES_FILE${NC}"
echo -e "${YELLOW}💡 You can now import types like: import type { Database } from '@/types/supabase'${NC}" 